spring.application.name=checkinn
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/employees
spring.datasource.username=root
spring.datasource.password=
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
security.jwt.secret=RV4CDNTnymUp4HaCydyQIM+ytIrMWG905i3N4MLapRc=
security.jwt.secret.issuer=swer-soa
security.jwt.secret.access-token-minutes=60
security.jwt.secret.refresh-token-days=7